#!/bin/bash
# check if there is a $1 (an argument)
# if its empty, dont do anything
# if its not empty, set SERVER_NAME to $1
if [ -z "$1" ]; then
	echo "need servername!"
	exit 1
else
    SERVER_NAME=$1
fi

#set server by using $1, eg. "./backup servername"
BACKUP_FILE_NAME_WORLD=$(date "+%Y.%m.%d-%H.%M")_world-$SERVER_NAME.7z
BACKUP_FILE_NAME_SERVER=$(date "+%Y.%m.%d-%H.%M")_server-$SERVER_NAME.7z
MONTH_FOLDER_NAME=$(date "+%B")
YEAR_FOLDER_NAME=$(date "+%Y")
RCLONE_UPLOAD_REMOTE=mc:/$SERVER_NAME

LOGFILE=$HOME/logs/backups.log
SERVER_DIR=/opt/minecraft
TMP_DIR=$HOME/tmp/$SERVER_NAME


# default settings
#
# mc:
# └── February
#     └── server
#         ├── 2021.02.01-22.00_server-survival.7z
#         ├── 2021.02.02-22.00_server-survival.7z
#         ├── 2021.02.02-22.00_server-survival.7z
#     └── world
#         ├── 2021.02.01-22.00_world-survival.7z
#         ├── 2021.02.02-22.00_world-survival.7z
#         └── 2021.02.02-22.00_world-survival.7z
# └── March
#     └── server
#         ├── 2021.03.01-22.00_server-survival.7z
#         ├── 2021.03.02-22.00_server-survival.7z
#         ├── 2021.03.02-22.00_server-survival.7z
#     └── world
#         ├── 2021.03.01-22.00_world-survival.7z
#         ├── 2021.03.02-22.00_world-survival.7z
#         └── 2021.03.02-22.00_world-survival.7z
#

############################################
## NO NECESSARY CHANGES BEYOND THIS LINE! ##
############################################

#stop minecraft server
printf "" | tee $LOGFILE
echo "backing up minecraft server $SERVER_NAME" | tee -a $LOGFILE
echo "stopping minecraft server..." | tee -a $LOGFILE
systemctl stop mc@$SERVER_NAME


#backup world
echo "creating archives..." | tee -a $LOGFILE
#sleep 3
if [ -d "$SERVER_DIR/$SERVER_NAME/world_nether" ] || [ -d "$SERVER_DIR/$SERVER_NAME/world_the_end" ]; then
		echo "before error world spigot"
		/usr/local/bin/7z a "$TMP_DIR/$YEAR_FOLDER_NAME/$MONTH_FOLDER_NAME/world/$BACKUP_FILE_NAME_WORLD" "$SERVER_DIR/$SERVER_NAME/world" "$SERVER_DIR/$SERVER_NAME/world_nether" "$SERVER_DIR/$SERVER_NAME/world_the_end" -mx0 |& tee -a $LOGFILE
 	else
		/usr/local/bin/7z a "$TMP_DIR/$YEAR_FOLDER_NAME/$MONTH_FOLDER_NAME/world/$BACKUP_FILE_NAME_WORLD" "$SERVER_DIR/$SERVER_NAME/world" -mx0 |& tee -a $LOGFILE
fi

#backup server
echo "before error server"
/usr/local/bin/7z a "$TMP_DIR/$YEAR_FOLDER_NAME/$MONTH_FOLDER_NAME/server/$BACKUP_FILE_NAME_SERVER" "$SERVER_DIR/$SERVER_NAME" -mx0 |& tee -a $LOGFILE

echo ""
echo "starting minecraft server..." | tee -a $LOGFILE
echo "uploading the files to $RCLONE_UPLOAD_REMOTE" | tee -a $LOGFILE
echo "" | tee -a $LOGFILE
systemctl start mc@$SERVER_NAME

rclone move $TMP_DIR $RCLONE_UPLOAD_REMOTE --delete-empty-src-dirs -v |& tee -a $LOGFILE
echo "uploading done" | tee -a $LOGFILE
echo "script done" | tee -a $LOGFILE
